### ISSUE TITLE
sqlite3 database locked

### ISSUE THREAD

**Issue by ars1614** [wmw9/cyberdrop-dl#18]
I am using the app on a raspberry pi3 ubuntu:

Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy

When I execute the batch from the folder, it returns this error:
```Starting Cyberdrop-DL
We are running version 4.2.28 of Cyberdrop Downloader
Traceback (most recent call last):
  File "/home/ars/.local/bin/cyberdrop-dl", line 8, in <module>
    sys.exit(main())
  File "/home/ars/.local/lib/python3.10/site-packages/cyberdrop_dl/main.py", line 303, in main
    loop.run_until_complete(director(args, links))
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/ars/.local/lib/python3.10/site-packages/cyberdrop_dl/main.py", line 245, in director
    await SQL_Helper.sql_initialize()
  File "/home/ars/.local/lib/python3.10/site-packages/cyberdrop_dl/base_functions/sql_helper.py", line 54, in sql_initialize
    await self._pre_allocate()
  File "/home/ars/.local/lib/python3.10/site-packages/cyberdrop_dl/base_functions/sql_helper.py", line 114, in _pre_allocate
    self.curs.execute(pre_alloc)
sqlite3.OperationalError: database is locked
```

When I execute it from a Windows OS, it works nicely.

**Comment by evan-sm** [comment]
You're trying to run another python application, try `type -a cyberdrop-dl` to see full path

**Comment by ars1614** [comment]
I had two of them: 
/home/MyUser/.local/bin/cyberdrop-dl
/usr/local/bin/cyberdrop-dl

I renamed the one from /usr/local/bin and it's giving the same error.
